---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  openstack-synchronizer
spec:
  selector:
    matchLabels:
      app: openstack-synchronizer
  template:
    metadata:
      labels:
        app:  openstack-synchronizer
    spec:
      containers:
      - image:  xosproject/openstack-synchronizer:master
        name:  openstack-synchronizer
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
        env:
        - name:  SERVICE_NAME
          value:  openstack-synchronizer
        volumeMounts:
        - mountPath: /opt/xos/xos_config.yaml
          name: config
          readOnly: true
        - mountPath: /opt/cord_profile/node_key
          name: node-key
          readOnly: true
        - mountPath: /opt/xos/services/openstack/credentials
          name: credentials
          readOnly: true
        - mountPath: /usr/local/share/ca-certificates/local_certs.crt
          name: local-certs
          readOnly: true
        - mountPath: /opt/xos/images
          name: images
          readOnly: true
      volumes:
      - name: config
        hostPath:
          path: /opt/cord_profile/xos_config_synchronizer.yaml
      - name: node-key
        hostPath:
          path: /opt/cord_profile/node_key
      - name: credentials
        hostPath:
          path: /opt/credentials
      - name: local-certs
        hostPath:
          path: /opt/cord_profile/im_cert_chain.pem
      - name: images
        hostPath:
          path: /opt/cord_profile/images
          