---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  volt-synchronizer
spec:
  selector:
    matchLabels:
      app: volt-synchronizer
  template:
    metadata:
      labels:
        app:  volt-synchronizer
    spec:
      containers:
      - image:  xosproject/volt-synchronizer:master
        name:  volt-synchronizer
        env:
        - name:  SERVICE_NAME
          value:  xos-volt-synchronizer
        volumeMounts:
        - mountPath: /opt/xos/xos_config.yaml
          name: config
          readOnly: true
        - mountPath: /opt/cord_profile/node_key
          name: node-key
          readOnly: true
        - mountPath: /opt/xos/services/rcord/credentials
          name: credentials
          readOnly: true
        - mountPath: /usr/local/share/ca-certificates/local_certs.crt
          name: local-certs
          readOnly: true
      volumes:
      - name: config
        hostPath:
          path: /opt/cord_profile/xos_config_synchronizer.yaml
      - name: node-key
        hostPath:
          path: /opt/cord_profile/node_key
      - name: credentials
        hostPath:
          path: /opt/credentials
      - name: local-certs
        hostPath:
          path: /opt/cord_profile/im_cert_chain.pem